### PR TITLE
add test.js

### PR DESCRIPTION
**Pull request by TrustySteed**
just a test...

**Tickets:** [74718](https://pestroutes.freshdesk.com/a/tickets/74718), [74719](https://pestroutes.freshdesk.com/a/tickets/74719), [74720](https://pestroutes.freshdesk.com/a/tickets/74720)

hello

### CODE REVIEW

**Review by dingflot — DISMISSED** [review]
testing the webhook for pull request event requested_changes

**Review by dingflot — COMMENTED** [review]
just leaving a comment to test the webhook

**Review by dingflot — CHANGES_REQUESTED** [review]
testing requesting changes for webhook again

**Comment by TrustySteed** [comment]
test closing pull request

**Comment by TrustySteed** [comment]
test reopening pr

**Review by dingflot — APPROVED** [review]
testing approved pr webhook

**Pull request merged**
