### PR TITLE
Create test2.js

### PR DESCRIPTION
**Pull request by TrustySteed**
**Ticket IDs :** 72858, 35869 34333
This is a repeat of #8615, but with a regression fix. The only changes made are to the way we call the cardType function... previously was calling via static keyword, now using PaymentProfile class name to call statically. Today, I discovered my error in testing previously, when I executed the createPaymentProfile test using my custom version of resources/classes/API/Tests/genericD

Tickets: [74718](http://pestroutes.freshdesk.com/a/tickets/74718), [74719](https://pestroutes.freshdesk.com/a/tickets/74719)

### CODE REVIEW

**Review by dingflot — DISMISSED** [review]
changes requested

**Review by dingflot — APPROVED** [review]
test

**Review by dingflot — APPROVED** [review]
approved again!

**Comment by TrustySteed** [comment]
test close pull request

**Comment by TrustySteed** [comment]
test reopen

**Comment by TrustySteed** [comment]
**Ticket IDs :** 72858, 35869 34333
This is a repeat of #8615, but with a regression fix. The only changes made are to the way we call the cardType function... previously was calling via static keyword, now using PaymentProfile class name to call statically. Today, I discovered my error in testing previously, when I executed the createPaymentProfile test using my custom version of resources/classes/API/Tests/genericD

Tickets: [74718](http://pestroutes.freshdesk.com/a/tickets/74718), [74719](https://pestroutes.freshdesk.com/a/tickets/74719)

**Comment by TrustySteed** [comment]
**Ticket IDs :** 55667, 44332 99771
This is a repeat of #8615, but with a regression fix. The only changes made are to the way we call the cardType function... previously was calling via static keyword, now using PaymentProfile class name to call statically. Today, I discovered my error in testing previously, when I executed the createPaymentProfile test using my custom version of resources/classes/API/Tests/genericD

Tickets: [98765](http://pestroutes.freshdesk.com/a/tickets/98765), [4321](https://pestroutes.freshdesk.com/a/tickets/4321)

**Pull request merged**
